In [41]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from imblearn.over_sampling import SMOTE

from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

from sklearn.metrics import confusion_matrix, classification_report
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

from sklearn.ensemble import VotingClassifier

In [42]:
df = pd.read_csv('diabetes.csv')
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [43]:
df.shape

(768, 9)

In [44]:
df.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531      69.105469      20.536458   79.799479   
std       3.369578   31.972618      19.355807      15.952218  115.244002   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   30.500000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [45]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [46]:
df['Outcome'].unique()

array([1, 0])

In [47]:
df['Outcome'].value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

In [48]:
# # prompt: draw paiplot graph for given dataset

# import matplotlib.pyplot as plt
# sns.pairplot(df, hue='Outcome')
# plt.show()


In [49]:
x = df.iloc[:, :-1]
y = df['Outcome']

x.ndim, y.ndim

(2, 1)

In [50]:
x.head(3)

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   

   DiabetesPedigreeFunction  Age  
0                     0.627   50  
1                     0.351   31  
2                     0.672   32

---
Over Sampling the data

In [51]:
# prompt: do over sampling using SMOTE

smote = SMOTE()
x_smote, y_smote = smote.fit_resample(x,y)

y_smote.value_counts()
# x_smote.value_counts()

Outcome
1    500
0    500
Name: count, dtype: int64

In [52]:
# x = x_smote
# y = y_smote

---
Standardizing the features (Feature Scaling)

In [53]:
# ss = StandardScaler()
# x = ss.fit_transform(x)

In [54]:
# x = pd.DataFrame(x, columns=df.columns[:-1])
# x.head()

In [55]:
# x.ndim

Spliting the data into training and testing sets

In [56]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=4)

Applying Logistic Regression

In [57]:
classifier = LogisticRegression(max_iter=500)
classifier.fit(x_train, y_train)

LogisticRegression(max_iter=500)

In [58]:
classifier.score(x_test, y_test), classifier.score(x_train, y_train)

(0.8116883116883117, 0.7719869706840391)

In [59]:
classifier.predict(x_test)

array([0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1])

Evaluating Models Performance

In [60]:
confusion_matrix(y_test, classifier.predict(x_test))

array([[90, 12],
       [17, 35]])

In [61]:
# classification_report(y_test, classifier.predict(x_test))

In [62]:
f1_score(y_test, classifier.predict(x_test)), recall_score(y_test, classifier.predict(x_test)), precision_score(y_test, classifier.predict(x_test))

(0.7070707070707071, 0.6730769230769231, 0.7446808510638298)

---

Using Decision tree

In [63]:
dt = DecisionTreeClassifier(criterion='entropy', max_depth=3)
dt.fit(x_train, y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=3)

In [64]:
dt.score(x_test, y_test), dt.score(x_train, y_train)

(0.8051948051948052, 0.7638436482084691)

In [65]:
confusion_matrix(y_test, dt.predict(x_test))

array([[88, 14],
       [16, 36]])

In [66]:
# for i in range(1, 10):
#   dt1 = DecisionTreeClassifier(criterion='entropy', max_depth=i)
#   dt1.fit(x_train, y_train)
#   print(i, dt1.score(x_test, y_test), dt1.score(x_train, y_train))

---
Random Forest

In [67]:
rf = RandomForestClassifier(n_estimators=10, criterion='entropy')
rf.fit(x_train, y_train)

rf.score(x_test, y_test), rf.score(x_train, y_train)

(0.7402597402597403, 0.993485342019544)

In [68]:
confusion_matrix(y_test, rf.predict(x_test))

array([[89, 13],
       [27, 25]])

---
SVC

In [69]:
svc = SVC(kernel='linear')
svc.fit(x_train, y_train)

svc.score(x_test, y_test), svc.score(x_train, y_train)

(0.7987012987012987, 0.7703583061889251)

In [70]:
confusion_matrix(y_test, svc.predict(x_test))

array([[89, 13],
       [18, 34]])

---
KNN

In [71]:
kn = KNeighborsClassifier(n_neighbors=60)
kn.fit(x_train, y_train)

kn.score(x_test, y_test), kn.score(x_train, y_train)

(0.7857142857142857, 0.7361563517915309)

---
Ensemble Learning

In [72]:
li = [('kn', KNeighborsClassifier(n_neighbors=60)), ('dt',  DecisionTreeClassifier(criterion='entropy', max_depth=3)), ('svc', SVC(kernel='linear'))]
# w = [10,10,10]

vc = VotingClassifier(estimators=li)
vc.fit(x_train, y_train)

vc.score(x_test, y_test), vc.score(x_train, y_train)

(0.7987012987012987, 0.7703583061889251)

In [73]:
confusion_matrix(y_test, vc.predict(x_test))

array([[90, 12],
       [19, 33]])

In [74]:
f1_score(y_test, vc.predict(x_test)), recall_score(y_test, vc.predict(x_test)), precision_score(y_test, vc.predict(x_test))

(0.6804123711340206, 0.6346153846153846, 0.7333333333333333)

### Making Predictive System

In [75]:
input_data = (5, 166, 72, 19, 175, 25.8, 0.587, 51)

# changing input data to numpy array
input_array = np.asarray(input_data)

# reshaping the size as we are predictinf for one instance
input_array_reshaped = input_array.reshape(1,-1)

prediction = vc.predict(input_array_reshaped)
print(prediction)

if (prediction[0] == 0):
    print('The person is diabetic')
else:
    print( 'The person is not diabetic')

[1]
The person is not diabetic


c:\ProgramData\anaconda3\envs\MachineLearning\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(
c:\ProgramData\anaconda3\envs\MachineLearning\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
c:\ProgramData\anaconda3\envs\MachineLearning\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


---

### Saving the ML model

In [76]:
# Creating a file name
filename = 'trained_model.sav'

In [77]:
import pickle

In [78]:
pickle.dump(vc, open(filename, 'wb'))

### Load the saved model

In [79]:
loaded_model = pickle.load(open(filename, 'rb'))

### Testing the model

In [80]:
input_data = (5, 166, 72, 19, 175, 25.8, 0.587, 51)

# changing input data to numpy array
input_array = np.asarray(input_data)

# reshaping the size as we are predictinf for one instance
input_array_reshaped = input_array.reshape(1,-1)

prediction = loaded_model.predict(input_array_reshaped)
print(prediction)

if (prediction[0] == 0):
    print('The person is not diabetic')
else:
    print( 'The person is diabetic')


[1]
The person is diabetic


c:\ProgramData\anaconda3\envs\MachineLearning\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(
c:\ProgramData\anaconda3\envs\MachineLearning\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
c:\ProgramData\anaconda3\envs\MachineLearning\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


---